### PR TITLE
fix protobuf message construction

### PR DESCRIPTION
**Pull request by cj-chung**
1. fix protobuf message construction to topology, network, and compute.
2. fix scenario update error
3. fix scenario deploy error

### CODE REVIEW

**Review by zzengcs — DISMISSED** [review]
LGTM

**Review by yanmo96 — DISMISSED** [review]
LGTM

**Review by yanmo96 — APPROVED** [review]
LGTM

**Review by zzengcs — APPROVED** [review]
LGTM

**Review by zzengcs — APPROVED** [review]
LGTM

**Review by yanmo96 — APPROVED** [review]
LGMT

**Review by yanmo96 — APPROVED** [review]
LGTM

**Review by zzengcs — APPROVED** [review]
LGTM

**Review by yanmo96 — APPROVED** [review]
LGTM

**Review by xieus — APPROVED** [review]

**Pull request merged**
