### PR TITLE
Added delete node function. Fixed #97 and #98

### LINKED ISSUE #97: Merak-Network: Delete return will hang

### PR DESCRIPTION
**Pull request by yanmo96**
This PR add the delete node function from https://github.com/futurewei-cloud/merak/issues/64
Address the the issue https://github.com/futurewei-cloud/merak/issues/97 , which is caused by a wait group in the wrong place. Which stoped process to write into channel, if it cannot write into channel, the Wait will never finish. Then the entire program will hang.
Address the issue https://github.com/futurewei-cloud/merak/issues/98 , fixed by empty the channel after every time I retrieve information from it.

### CODE REVIEW

**Comment by yanmo96** [comment]
Address the PR #64

**Comment by yanmo96** [comment]
Hi @cj-chung 
This PR add the delete node function from #64 
Address the the issue #97 , which is caused by a wait group in the wrong place. Which stoped process to write into channel, if it cannot write into channel, the Wait will never finish. Then the entire program will hang.  
Address the issue #98 , fixed by empty the channel after every time I retrieve information from it.

Thanks

**Comment by cj-chung** [comment]
@yanmo96 Please create a merak-network service container on .77 with your latest PR. We need to verify the change.

**Comment by yanmo96** [comment]
Will improve the code once node bulk deletion ability is added to Alcor https://github.com/futurewei-cloud/alcor/issues/755

**Review by cj-chung — APPROVED** [review]
LGTM

**Pull request merged**
