### PR TITLE
Evm Optimize

### PR DESCRIPTION
**Pull request by phudtran**
This PR adds the following:

- Reduce components use in EVM creation to a single Network Namespace 
- Original implementation involved
  - Veth-Pair
  - Bridge
  - Network Namespace
- Reduce the number of steps to create an EVM from **18** steps to **11** steps
- Reduce EVM packet latency by 33%
- Update design doc and diagram to reflect design change.
- Fix an issue in merak topology containerport for vhost resulting in failed deployments
- Change to temporalite in the dev environment for quicker deployment
- Update the delete workflow to reflect new EVM design

### CODE REVIEW

**Review by cj-chung — COMMENTED** [review]
@phudtran You did a lot of change in merak-agent, did you cover the unit test for them in this PR too?

**Comment by phudtran** [comment]
> @phudtran You did a lot of changes in the merak-agent, did you cover the unit test for them in this PR too?

No, will cover unit tests for compute and agent after this PR.

**Review by cj-chung — APPROVED** [review]
LGTM

**Review by xieus — COMMENTED** [review]
@phudtran After the PR is merged to main, will it potentially change the deployment experience listed on the page https://github.com/futurewei-cloud/merak#kind-simple-deployment-and-e2e-test? We may need to have some sort of CI/CD jobs to ensure no broken issue is introduced.

**Comment by phudtran** [comment]
> @phudtran After the PR is merged to main, will it potentially change the deployment experience listed on the page https://github.com/futurewei-cloud/merak#kind-simple-deployment-and-e2e-test? We may need to have some sort of CI/CD jobs to ensure no broken issue is introduced.

I've tested to confirm it doesn't affect deployment. But yes we should run the deployment scenario and e2e test in CI. We are actually one step away from doing this. Just need a script to confirm that all pods are up before running the teste2e tool.

**Pull request merged**
